### ISSUE TITLE
Still work?

### ISSUE THREAD

**Issue by RaDeleon** [rbdixon/edope#1]

**Comment by RaDeleon** [comment]
Having issue with usbq not being found during install

**Comment by rbdixon** [comment]
You can find usbq here: https://github.com/carvesystems/usbq

**Comment by RaDeleon** [comment]
Installed USBQ and got this while trying to run it

Traceback (most recent call last):
  File "/usr/local/bin/usbq", line 11, in <module>
    load_entry_point('usbq==0.1.0', 'console_scripts', 'usbq')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/usbq-0.1.0-py2.7.egg/usbq/cli.py", line 91
    click.echo(f'usbq version {__version__}\n')
                                             ^
SyntaxError: invalid syntax

**Comment by RaDeleon** [comment]
and then this while trying to run edope

edope
Traceback (most recent call last):
  File "/usr/local/bin/edope", line 11, in <module>
    load_entry_point('edope==0.1.0', 'console_scripts', 'edope')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/edope-0.1.0-py2.7.egg/edope/cli.py", line 33
    click.echo(f'edope version {__version__}\n')
                                              ^
SyntaxError: invalid syntax

**Comment by rbdixon** [comment]
You'll need a newer version of Python.
